import { chmod, copyFile, mkdir, readdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";

export type AgentPackKind = "claude-code" | "codex" | "gemini-cli";

export interface AgentPackMetadata {
  kind: AgentPackKind;
  label: string;
  files: string[];
}

export interface AgentPackExportResult {
  kind: AgentPackKind;
  label: string;
  outDir: string;
  sharedFiles: string[];
  packFiles: string[];
  manifestPath: string;
  readmePath: string;
}

const TRACK_VERSION = "0.1.0";

const PACKS: Record<AgentPackKind, AgentPackMetadata> = {
  "claude-code": {
    kind: "claude-code",
    label: "Claude Code",
    files: ["README.md", "CLAUDE_PROMPT.md", "COMMAND_PATTERNS.md"],
  },
  codex: {
    kind: "codex",
    label: "Codex",
    files: ["README.md", "OPERATING_GUIDE.md", "COMMANDS_AND_MCP.md"],
  },
  "gemini-cli": {
    kind: "gemini-cli",
    label: "Gemini CLI",
    files: ["README.md", "OPERATING_GUIDE.md", "COMMANDS_AND_MCP.md"],
  },
};

const SHARED_FILES = ["README.md", "bin/track-context.sh", "bin/track-update.sh"];

export function listAgentPackKinds(): AgentPackKind[] {
  return Object.keys(PACKS) as AgentPackKind[];
}

export function normalizeAgentPackKind(raw: string | undefined): AgentPackKind | undefined {
  if (!raw) {
    return undefined;
  }

  const normalized = raw.trim().toLowerCase();
  if (normalized === "claude") {
    return "claude-code";
  }
  if (normalized === "gemini") {
    return "gemini-cli";
  }
  if (normalized in PACKS) {
    return normalized as AgentPackKind;
  }
  return undefined;
}

export function resolveDefaultAgentPackOutDir(repoRoot: string, kind: AgentPackKind): string {
  return path.join(repoRoot, ".track", "agent-packs", kind);
}

export async function exportAgentPack(options: {
  repoRoot: string;
  kind: AgentPackKind;
  outDir?: string;
}): Promise<AgentPackExportResult> {
  const pack = PACKS[options.kind];
  const outDir = path.resolve(options.outDir ?? resolveDefaultAgentPackOutDir(options.repoRoot, pack.kind));
  const sharedSourceRoot = path.join(options.repoRoot, "agents", "shared");
  const packSourceRoot = path.join(options.repoRoot, "agents", pack.kind);
  const sharedTargetRoot = path.join(outDir, "shared");
  const packTargetRoot = path.join(outDir, pack.kind);

  await mkdir(outDir, { recursive: true });
  await mkdir(sharedTargetRoot, { recursive: true });
  await mkdir(packTargetRoot, { recursive: true });

  const sharedFiles = await Promise.all(
    SHARED_FILES.map(async (relativePath) => {
      await copyTrackedFile(path.join(sharedSourceRoot, relativePath), path.join(sharedTargetRoot, relativePath));
      return path.join("shared", relativePath);
    })
  );

  const packFiles = await Promise.all(
    pack.files.map(async (relativePath) => {
      await copyTrackedFile(path.join(packSourceRoot, relativePath), path.join(packTargetRoot, relativePath));
      return path.join(pack.kind, relativePath);
    })
  );

  const readmePath = path.join(outDir, "README.md");
  const manifestPath = path.join(outDir, "manifest.json");

  await writeFile(
    readmePath,
    [
      "# Track Agent Pack Export",
      "",
      `This bundle contains the shared Track helper set plus the ${pack.label} operating pack.`,
      "",
      "## Contents",
      "",
      "- `shared/`",
      `- \`${pack.kind}/\``,
      "- `manifest.json`",
      "",
      "## Usage",
      "",
      "1. Read the client pack README first.",
      "2. Use the shared helper scripts under `shared/bin/` for context and mutations.",
      "3. Keep the repo-local `.track` files as the source of truth.",
      "",
      "Generated by `track pack export`.",
      "",
    ].join("\n"),
    "utf8"
  );

  await writeFile(
    manifestPath,
    JSON.stringify(
      {
        version: 1,
        track_version: TRACK_VERSION,
        tool: pack.kind,
        label: pack.label,
        exported_at: new Date().toISOString(),
        files: [...sharedFiles, ...packFiles, "README.md", "manifest.json"],
      },
      null,
      2
    ),
    "utf8"
  );

  return {
    kind: pack.kind,
    label: pack.label,
    outDir,
    sharedFiles,
    packFiles,
    manifestPath,
    readmePath,
  };
}

export function summarizeAgentPackExport(result: AgentPackExportResult): string {
  const fileCount = result.sharedFiles.length + result.packFiles.length + 2;
  return [
    `Exported ${result.label} pack`,
    `OUT      ${result.outDir}`,
    `FILES    ${fileCount}`,
    `SHARED   ${result.sharedFiles.join(", ")}`,
    `PACK     ${result.packFiles.join(", ")}`,
  ].join("\n");
}

async function copyTrackedFile(sourcePath: string, targetPath: string): Promise<void> {
  await mkdir(path.dirname(targetPath), { recursive: true });
  await copyFile(sourcePath, targetPath);
  const sourceStat = await stat(sourcePath);
  await chmod(targetPath, sourceStat.mode);
}

export async function loadAgentPackManifest(manifestPath: string): Promise<unknown> {
  const raw = await readFile(manifestPath, "utf8");
  return JSON.parse(raw);
}

export async function listAgentPackFiles(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const absolutePath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      const nested = await listAgentPackFiles(absolutePath);
      for (const nestedPath of nested) {
        files.push(path.join(entry.name, nestedPath));
      }
      continue;
    }
    files.push(entry.name);
  }
  return files.sort();
}
